# name: Matrix Configuration
# on: push

# jobs:
#   docker_linux:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Echo Docker Details
#         run: docker info

#       - name: Run Image
#         run: docker run hello-world


#   deploy_on_windows:
#     runs-on: windows-latest
#     steps:
#       - name: Echo docker detail
#         run: docker info

#       - name: Run Image
#         run: docker run hello-world

name: matrix configuration
on: push
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo docker details
        run: docker info

      - name: Run images on ${{ matrix.images }}
        run: docker run ${{ matrix.images }}
      
       


    