name: My second workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: List Repo Files
        run: ls -ltra

      - name: Install cowsay program
        run: chmod 777 ascii-script.sh
       
      - name: Install cowsay program
        run: ./ascii-script.sh



